services:
  mysql:
    image: mysql:8.0
    # 'mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - mysql:/var/lib/mysql
        - ./initdb.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: dbname
        MYSQL_USER: dbname
        MYSQL_PASSWORD: userpassword
    ports:
        - "3306:3306"
volumes:
  mysql:
