apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foo
  name: foo
  namespace: test-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  strategy: {}
  template:
    metadata:
      labels:
        app: foo
        ContactPerson: Username
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: {}
status: {}
