# permissions for end users to view traefiks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: traefik-viewer-role
rules:
- apiGroups:
  - ingress.demo.morawskim.pl
  resources:
  - traefiks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.demo.morawskim.pl
  resources:
  - traefiks/status
  verbs:
  - get
