
project: noip-client

# Set this if you want to carry over parent process' environment variables
# carry_env: true


#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  region: env:AWS_REGION    # you can get env variables with the 'env:' prefix, for default values if env not found use comma. Example: env:AWS_REGION,{DEFAULT_VALUE}
  stage: development


#
# Providers
#
providers:
  # Override default configuration: https://github.com/gopasspw/gopass/blob/master/docs/config.md
  gopass:
    env_sync:
      path: tokens/GHCR
    env:
      GHCR_TOKEN:
        path: tokens/GHCR
