<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace PB;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>demo.OrderItem</code>
 */
class OrderItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sku = 1;</code>
     */
    protected $sku = '';
    /**
     * Generated from protobuf field <code>int32 quantity = 2;</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>int32 unitPrice = 3;</code>
     */
    protected $unitPrice = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sku
     *     @type int $quantity
     *     @type int $unitPrice
     * }
     */
    public function __construct($data = NULL) {
        \PB\Metadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sku = 1;</code>
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * Generated from protobuf field <code>string sku = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSku($var)
    {
        GPBUtil::checkString($var, True);
        $this->sku = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 2;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unitPrice = 3;</code>
     * @return int
     */
    public function getUnitPrice()
    {
        return $this->unitPrice;
    }

    /**
     * Generated from protobuf field <code>int32 unitPrice = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUnitPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->unitPrice = $var;

        return $this;
    }

}

