<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace PB;

use UnexpectedValueException;

/**
 * Protobuf type <code>demo.OrderStatus</code>
 */
class OrderStatus
{
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_UNSPECIFIED = 0;</code>
     */
    const ORDER_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_NEW = 1;</code>
     */
    const ORDER_STATUS_NEW = 1;
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_ACCEPTED = 2;</code>
     */
    const ORDER_STATUS_ACCEPTED = 2;
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_PAID = 3;</code>
     */
    const ORDER_STATUS_PAID = 3;
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_SENT = 4;</code>
     */
    const ORDER_STATUS_SENT = 4;
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_CANCALED = 5;</code>
     */
    const ORDER_STATUS_CANCALED = 5;

    private static $valueToName = [
        self::ORDER_STATUS_UNSPECIFIED => 'ORDER_STATUS_UNSPECIFIED',
        self::ORDER_STATUS_NEW => 'ORDER_STATUS_NEW',
        self::ORDER_STATUS_ACCEPTED => 'ORDER_STATUS_ACCEPTED',
        self::ORDER_STATUS_PAID => 'ORDER_STATUS_PAID',
        self::ORDER_STATUS_SENT => 'ORDER_STATUS_SENT',
        self::ORDER_STATUS_CANCALED => 'ORDER_STATUS_CANCALED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

